name: gp_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  very_good_analysis: ^4.0.0+1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dartz: ^0.10.1
  dio: ^5.1.1
  get_it: ^7.2.0
  lottie: ^2.3.1
  google_fonts: ^4.0.3
  flutter_swiper_view: ^1.1.8
  go_router: ^6.5.5
  http: ^0.13.5
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie_animations/
    - assets/images/
    - assets/icons/