exports.categoriesFilter = {
    sofa: "sofa",
    table: "table",
    bed: "bed",
    chair: "chair",
    cabinet: "dresser",
    nightstand: "dresser",
    closet: "dresser",
    cupboard: "accessories",
    lamp: "accessories",
    shelf: "accessories",
    curtains: "accessories",
    "tv stand": "accessories",
    sideboard: "accessories",
};
